// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: userreg.proto

package wtproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//用户登录请求
type CSUserLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accountid string `protobuf:"bytes,1,opt,name=accountid,proto3" json:"accountid,omitempty"` //账号
	Passwd    string `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`       //密码
	Phone     string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`         //留备用电话
}

func (x *CSUserLogin) Reset() {
	*x = CSUserLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userreg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSUserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSUserLogin) ProtoMessage() {}

func (x *CSUserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_userreg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSUserLogin.ProtoReflect.Descriptor instead.
func (*CSUserLogin) Descriptor() ([]byte, []int) {
	return file_userreg_proto_rawDescGZIP(), []int{0}
}

func (x *CSUserLogin) GetAccountid() string {
	if x != nil {
		return x.Accountid
	}
	return ""
}

func (x *CSUserLogin) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

func (x *CSUserLogin) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

//用户登录回复
type SCUserLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errid int32  `protobuf:"varint,1,opt,name=errid,proto3" json:"errid,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SCUserLogin) Reset() {
	*x = SCUserLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userreg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUserLogin) ProtoMessage() {}

func (x *SCUserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_userreg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUserLogin.ProtoReflect.Descriptor instead.
func (*SCUserLogin) Descriptor() ([]byte, []int) {
	return file_userreg_proto_rawDescGZIP(), []int{1}
}

func (x *SCUserLogin) GetErrid() int32 {
	if x != nil {
		return x.Errid
	}
	return 0
}

func (x *SCUserLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

//用户呼叫请求
type CSUserCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caller   string `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`     //发起呼叫的人的账号
	Becalled string `protobuf:"bytes,2,opt,name=becalled,proto3" json:"becalled,omitempty"` //被呼叫人的账号
}

func (x *CSUserCall) Reset() {
	*x = CSUserCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userreg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSUserCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSUserCall) ProtoMessage() {}

func (x *CSUserCall) ProtoReflect() protoreflect.Message {
	mi := &file_userreg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSUserCall.ProtoReflect.Descriptor instead.
func (*CSUserCall) Descriptor() ([]byte, []int) {
	return file_userreg_proto_rawDescGZIP(), []int{2}
}

func (x *CSUserCall) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *CSUserCall) GetBecalled() string {
	if x != nil {
		return x.Becalled
	}
	return ""
}

//服务器转发呼叫请求给被呼叫人
type SCNotifyBeCalled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caller   string `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`     //发起呼叫的人的账号
	Becalled string `protobuf:"bytes,2,opt,name=becalled,proto3" json:"becalled,omitempty"` //被呼叫人的账号
}

func (x *SCNotifyBeCalled) Reset() {
	*x = SCNotifyBeCalled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userreg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCNotifyBeCalled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCNotifyBeCalled) ProtoMessage() {}

func (x *SCNotifyBeCalled) ProtoReflect() protoreflect.Message {
	mi := &file_userreg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCNotifyBeCalled.ProtoReflect.Descriptor instead.
func (*SCNotifyBeCalled) Descriptor() ([]byte, []int) {
	return file_userreg_proto_rawDescGZIP(), []int{3}
}

func (x *SCNotifyBeCalled) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *SCNotifyBeCalled) GetBecalled() string {
	if x != nil {
		return x.Becalled
	}
	return ""
}

//被呼叫人回复消息给服务器
type CSReplyBeCalled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caller   string `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`     //发起呼叫的人的账号
	Becalled string `protobuf:"bytes,2,opt,name=becalled,proto3" json:"becalled,omitempty"` //被呼叫的人的账号
	Agree    bool   `protobuf:"varint,3,opt,name=agree,proto3" json:"agree,omitempty"`      //是否同意
}

func (x *CSReplyBeCalled) Reset() {
	*x = CSReplyBeCalled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userreg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSReplyBeCalled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSReplyBeCalled) ProtoMessage() {}

func (x *CSReplyBeCalled) ProtoReflect() protoreflect.Message {
	mi := &file_userreg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSReplyBeCalled.ProtoReflect.Descriptor instead.
func (*CSReplyBeCalled) Descriptor() ([]byte, []int) {
	return file_userreg_proto_rawDescGZIP(), []int{4}
}

func (x *CSReplyBeCalled) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *CSReplyBeCalled) GetBecalled() string {
	if x != nil {
		return x.Becalled
	}
	return ""
}

func (x *CSReplyBeCalled) GetAgree() bool {
	if x != nil {
		return x.Agree
	}
	return false
}

//服务器回复发起人呼叫结果
type SCUserCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errid    int32  `protobuf:"varint,1,opt,name=errid,proto3" json:"errid,omitempty"`      //0，成功，非0失败
	Caller   string `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`     //发起呼叫的人的账号
	Becalled string `protobuf:"bytes,3,opt,name=becalled,proto3" json:"becalled,omitempty"` //被呼叫人的账号
	Phone    string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`       //如果被呼叫人不在，返回备注电话
}

func (x *SCUserCall) Reset() {
	*x = SCUserCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userreg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUserCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUserCall) ProtoMessage() {}

func (x *SCUserCall) ProtoReflect() protoreflect.Message {
	mi := &file_userreg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUserCall.ProtoReflect.Descriptor instead.
func (*SCUserCall) Descriptor() ([]byte, []int) {
	return file_userreg_proto_rawDescGZIP(), []int{5}
}

func (x *SCUserCall) GetErrid() int32 {
	if x != nil {
		return x.Errid
	}
	return 0
}

func (x *SCUserCall) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *SCUserCall) GetBecalled() string {
	if x != nil {
		return x.Becalled
	}
	return ""
}

func (x *SCUserCall) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

//服务器通知呼叫人和被呼叫人进行视频语音通话
type SCNotifyChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caller   string `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`     //发起呼叫的人的账号
	Becalled string `protobuf:"bytes,2,opt,name=becalled,proto3" json:"becalled,omitempty"` //被呼叫的人的账号
	Roomid   string `protobuf:"bytes,3,opt,name=roomid,proto3" json:"roomid,omitempty"`     //用于通信的rommid
}

func (x *SCNotifyChat) Reset() {
	*x = SCNotifyChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userreg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCNotifyChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCNotifyChat) ProtoMessage() {}

func (x *SCNotifyChat) ProtoReflect() protoreflect.Message {
	mi := &file_userreg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCNotifyChat.ProtoReflect.Descriptor instead.
func (*SCNotifyChat) Descriptor() ([]byte, []int) {
	return file_userreg_proto_rawDescGZIP(), []int{6}
}

func (x *SCNotifyChat) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *SCNotifyChat) GetBecalled() string {
	if x != nil {
		return x.Becalled
	}
	return ""
}

func (x *SCNotifyChat) GetRoomid() string {
	if x != nil {
		return x.Roomid
	}
	return ""
}

//客户端终止通话
type CSTerminateChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caller   string `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`     //发起呼叫的人的账号
	Becalled string `protobuf:"bytes,2,opt,name=becalled,proto3" json:"becalled,omitempty"` //被呼叫的人的账号
	Roomid   string `protobuf:"bytes,3,opt,name=roomid,proto3" json:"roomid,omitempty"`     //用于通信的rommid
}

func (x *CSTerminateChat) Reset() {
	*x = CSTerminateChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userreg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSTerminateChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSTerminateChat) ProtoMessage() {}

func (x *CSTerminateChat) ProtoReflect() protoreflect.Message {
	mi := &file_userreg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSTerminateChat.ProtoReflect.Descriptor instead.
func (*CSTerminateChat) Descriptor() ([]byte, []int) {
	return file_userreg_proto_rawDescGZIP(), []int{7}
}

func (x *CSTerminateChat) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *CSTerminateChat) GetBecalled() string {
	if x != nil {
		return x.Becalled
	}
	return ""
}

func (x *CSTerminateChat) GetRoomid() string {
	if x != nil {
		return x.Roomid
	}
	return ""
}

//服务器回复终止通话
type SCTerminateChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errid    int32  `protobuf:"varint,1,opt,name=errid,proto3" json:"errid,omitempty"`
	Caller   string `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`     //发起呼叫的人的账号
	Becalled string `protobuf:"bytes,3,opt,name=becalled,proto3" json:"becalled,omitempty"` //被呼叫的人的账号
	Roomid   string `protobuf:"bytes,4,opt,name=roomid,proto3" json:"roomid,omitempty"`     //用于通信的rommid
}

func (x *SCTerminateChat) Reset() {
	*x = SCTerminateChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userreg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCTerminateChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCTerminateChat) ProtoMessage() {}

func (x *SCTerminateChat) ProtoReflect() protoreflect.Message {
	mi := &file_userreg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCTerminateChat.ProtoReflect.Descriptor instead.
func (*SCTerminateChat) Descriptor() ([]byte, []int) {
	return file_userreg_proto_rawDescGZIP(), []int{8}
}

func (x *SCTerminateChat) GetErrid() int32 {
	if x != nil {
		return x.Errid
	}
	return 0
}

func (x *SCTerminateChat) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *SCTerminateChat) GetBecalled() string {
	if x != nil {
		return x.Becalled
	}
	return ""
}

func (x *SCTerminateChat) GetRoomid() string {
	if x != nil {
		return x.Roomid
	}
	return ""
}

var File_userreg_proto protoreflect.FileDescriptor

var file_userreg_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x77, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x0b, 0x43, 0x53, 0x55, 0x73,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x22, 0x39, 0x0a, 0x0b, 0x53, 0x43, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x40,
	0x0a, 0x0a, 0x43, 0x53, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64,
	0x22, 0x46, 0x0a, 0x10, 0x53, 0x43, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x42, 0x65, 0x43, 0x61,
	0x6c, 0x6c, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x62, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x22, 0x5b, 0x0a, 0x0f, 0x43, 0x53, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x61, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c,
	0x6c, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x67, 0x72, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x61, 0x67, 0x72, 0x65, 0x65, 0x22, 0x6c, 0x0a, 0x0a, 0x53, 0x43, 0x55, 0x73, 0x65, 0x72, 0x43,
	0x61, 0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6c,
	0x6c, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x22, 0x5a, 0x0a, 0x0c, 0x53, 0x43, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43,
	0x68, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x62,
	0x65, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x65, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x22,
	0x5d, 0x0a, 0x0f, 0x43, 0x53, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x68,
	0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65,
	0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x65,
	0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x22, 0x73,
	0x0a, 0x0f, 0x53, 0x43, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x62, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x62, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_userreg_proto_rawDescOnce sync.Once
	file_userreg_proto_rawDescData = file_userreg_proto_rawDesc
)

func file_userreg_proto_rawDescGZIP() []byte {
	file_userreg_proto_rawDescOnce.Do(func() {
		file_userreg_proto_rawDescData = protoimpl.X.CompressGZIP(file_userreg_proto_rawDescData)
	})
	return file_userreg_proto_rawDescData
}

var file_userreg_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_userreg_proto_goTypes = []interface{}{
	(*CSUserLogin)(nil),      // 0: wtproto.CSUserLogin
	(*SCUserLogin)(nil),      // 1: wtproto.SCUserLogin
	(*CSUserCall)(nil),       // 2: wtproto.CSUserCall
	(*SCNotifyBeCalled)(nil), // 3: wtproto.SCNotifyBeCalled
	(*CSReplyBeCalled)(nil),  // 4: wtproto.CSReplyBeCalled
	(*SCUserCall)(nil),       // 5: wtproto.SCUserCall
	(*SCNotifyChat)(nil),     // 6: wtproto.SCNotifyChat
	(*CSTerminateChat)(nil),  // 7: wtproto.CSTerminateChat
	(*SCTerminateChat)(nil),  // 8: wtproto.SCTerminateChat
}
var file_userreg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userreg_proto_init() }
func file_userreg_proto_init() {
	if File_userreg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userreg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSUserLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userreg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUserLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userreg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSUserCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userreg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCNotifyBeCalled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userreg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSReplyBeCalled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userreg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUserCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userreg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCNotifyChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userreg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSTerminateChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userreg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCTerminateChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userreg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userreg_proto_goTypes,
		DependencyIndexes: file_userreg_proto_depIdxs,
		MessageInfos:      file_userreg_proto_msgTypes,
	}.Build()
	File_userreg_proto = out.File
	file_userreg_proto_rawDesc = nil
	file_userreg_proto_goTypes = nil
	file_userreg_proto_depIdxs = nil
}
