// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: userreg.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CSUserReg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accountid int32 `protobuf:"varint,1,opt,name=accountid,proto3" json:"accountid,omitempty"`
	Token     int32 `protobuf:"varint,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CSUserReg) Reset() {
	*x = CSUserReg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userreg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSUserReg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSUserReg) ProtoMessage() {}

func (x *CSUserReg) ProtoReflect() protoreflect.Message {
	mi := &file_userreg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSUserReg.ProtoReflect.Descriptor instead.
func (*CSUserReg) Descriptor() ([]byte, []int) {
	return file_userreg_proto_rawDescGZIP(), []int{0}
}

func (x *CSUserReg) GetAccountid() int32 {
	if x != nil {
		return x.Accountid
	}
	return 0
}

func (x *CSUserReg) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

type SCUserReg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errid     int32 `protobuf:"varint,1,opt,name=errid,proto3" json:"errid,omitempty"`
	Accountid int32 `protobuf:"varint,2,opt,name=accountid,proto3" json:"accountid,omitempty"`
	Token     int32 `protobuf:"varint,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SCUserReg) Reset() {
	*x = SCUserReg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userreg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUserReg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUserReg) ProtoMessage() {}

func (x *SCUserReg) ProtoReflect() protoreflect.Message {
	mi := &file_userreg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUserReg.ProtoReflect.Descriptor instead.
func (*SCUserReg) Descriptor() ([]byte, []int) {
	return file_userreg_proto_rawDescGZIP(), []int{1}
}

func (x *SCUserReg) GetErrid() int32 {
	if x != nil {
		return x.Errid
	}
	return 0
}

func (x *SCUserReg) GetAccountid() int32 {
	if x != nil {
		return x.Accountid
	}
	return 0
}

func (x *SCUserReg) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

var File_userreg_proto protoreflect.FileDescriptor

var file_userreg_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x09, 0x43, 0x53, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x55, 0x0a, 0x09, 0x53, 0x43, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_userreg_proto_rawDescOnce sync.Once
	file_userreg_proto_rawDescData = file_userreg_proto_rawDesc
)

func file_userreg_proto_rawDescGZIP() []byte {
	file_userreg_proto_rawDescOnce.Do(func() {
		file_userreg_proto_rawDescData = protoimpl.X.CompressGZIP(file_userreg_proto_rawDescData)
	})
	return file_userreg_proto_rawDescData
}

var file_userreg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_userreg_proto_goTypes = []interface{}{
	(*CSUserReg)(nil), // 0: proto.CSUserReg
	(*SCUserReg)(nil), // 1: proto.SCUserReg
}
var file_userreg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userreg_proto_init() }
func file_userreg_proto_init() {
	if File_userreg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userreg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSUserReg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userreg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUserReg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userreg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userreg_proto_goTypes,
		DependencyIndexes: file_userreg_proto_depIdxs,
		MessageInfos:      file_userreg_proto_msgTypes,
	}.Build()
	File_userreg_proto = out.File
	file_userreg_proto_rawDesc = nil
	file_userreg_proto_goTypes = nil
	file_userreg_proto_depIdxs = nil
}
